[user]
name = "Stephen Jennings"

[ui]
editor = "nvim"
diff-editor = "meld"
#diff-editor = "kdiff3" # doesn't seem to support deleting files
merge-editor = "kdiff3"

default-command = "logr"

diff.format = "git"

pager = ["delta", "--hunk-header-style", "plain"]
paginate = "auto"

[revsets]
# log = "@ | ancestors((remote_branches() | tags()).., 2) | trunk()"
# default:
log = 'default'

[revset-aliases]
'def' = 'default'
'default' = '@ | ancestors((immutable_heads() | no_log_heads()).., 2) | heads((immutable_heads() | no_log_heads()))'
'no_log_heads()' = 'none()'
'stack' = 'stack(@)'
#'stack(from)' = 'trunk()..(from::) | (trunk()..from)-'
'stack(from)' = 'trunk()..(from::) | ancestors(trunk()..(from::), 2)'
'branches_in_stack()' = 'remote_branches() & stack()'
'slice' = 'slice(@)'
'slice(from)' = 'trunk()::(from::)'
'behind' = 'ancestors((trunk()..branches())::, 2)'
'hanging' = "branches() | remote_branches() | tags()"

[aliases]
logr = ["log", "--reversed"]
# viewing history
behind = ["logr", "-r", "behind"]
stack = ["logr", "-r", "stack"]
mine = ["logr", "-r", "trunk() | (behind & mine())"]
hanging = ["logr", "-r", "ancestors(hanging.., 2)"]

# useful for getting history of a file
history = ["logr", "-r", "..@"]

# navigating
n = ["next", "--edit"]
p = ["prev", "--edit"]

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'

