# personal stuff

brew "ansible"
brew "asciinema"
brew "automake"
brew "awscli"
brew "azure-cli"
brew "b2-tools"
brew "bat"
brew "cmake"
brew "ctags"
brew "fd" # used as FZF_DEFAULT_COMMAND
brew "fzf"
brew "git"
brew "git-delta"
brew "go"
brew "graphviz"
brew "htop"
brew "jq"
brew "neovim"
brew "netcat"
brew "nmap"
brew "nvm"
brew "openvpn"
brew "pandoc"
brew "pstree"
brew "pv"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "tarsnap"
brew "tmux"
brew "tree"
brew "yarn"
brew "z"

tap "hashicorp/tap"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/terraform-ls"

tap "homebrew/cask"
cask "azure-data-studio"
cask "docker"
cask "google-cloud-sdk"
cask "kdiff3"
cask "ngrok"
cask "obs"
cask "osxfuse"
cask "postman"
cask "suspicious-package"
cask "vagrant"
cask "vlc"

# for work

brew "ffmpeg"
brew "gstreamer"
cask "pritunl"

tap "octopusdeploy/taps"
brew "octopusdeploy/taps/octopuscli"
