[templates]
log_node = '''
    coalesce(
      if(!self, label("elided", "~")),
      label(
        separate(" ",
          if(current_working_copy, "working_copy"),
          if(immutable, "immutable"),
          if(conflict, "conflict"),
          if(self.contained_in("private()"), "private"),
        ),
        coalesce(
          if(current_working_copy, "@"),
          if(immutable, "◆"),
          if(conflict, "×"),
          if(self.contained_in("private()"), "◌"),
          "○",
        )
      )
    )
    '''

log = 'log'

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'
'hyperlink(url, text)' = '''
    concat(
      raw_escape_sequence("\e]8;;" ++ url ++ "\e\\"),
      text,
      raw_escape_sequence("\e]8;;\e\\"),
    )
'''
'render_bookmarks(commit)' = '''
    commit.bookmarks().map(|b|
      if(b.remote(),
        b,
        hyperlink(pr_base ++ b.name(), b),
      )
    )
'''

# Greatly simplified output, useful for demonstrations
'simple' = '''
    if(root,
      format_root_commit(self),
      label(if(current_working_copy, "working_copy"),
        concat(
          separate(" ",
            format_short_change_id_with_hidden_and_divergent_info(self),
            format_short_commit_id(commit_id),
            surround("[", "]", bookmarks),
            if(conflict, label("conflict", "conflict")),
          ),
          "\n",
          separate(" ",
            if(empty, label("empty", "(empty)")),
            if(description,
              description.first_line(),
            ),
          ),
          "\n\n",
        )
      )
    )
    '''

log = '''
    if(root,
      format_root_commit(self),
      label(if(current_working_copy, "working_copy"),
        concat(
          separate(" ",
            format_short_change_id_with_hidden_and_divergent_info(self),
            format_short_signature(author),
            if(!committer.email(), email_placeholder),
            format_timestamp(committer.timestamp()),
            render_bookmarks(self),
            tags,
            working_copies,
            format_short_commit_id(commit_id),
            if(conflict, label("conflict", "conflict")),
          ) ++ "\n",
          separate(" ",
            if(empty, label("empty", "(empty)")),
            if(description,
              description.first_line(),
              label(if(empty, "empty"), description_placeholder),
            ),
          ) ++ "\n",
        ),
      )
    )
    '''

log_comfortable = 'log ++ "\n"'

pr_base = '"undefined"'
