[user]
name = "Stephen Jennings"

[git]
push-branch-prefix = 'jennings/push-'

[ui]
editor = "nvim -n"
diff-editor = "bc"
merge-editor = "bc"

default-command = "logr"

# paginate with delta
diff.format = "git"
pager = ["delta", "--hunk-header-style", "plain", "--paging", "never"]
paginate = "auto"
log-synthetic-elided-nodes = false

[merge-tools.kdiff3]
edit-args = ["--merge", "--cs", "CreateBakFiles=0", "$left", "$left", "$right"]

[merge-tools.bc]
program = "bcomp"
diff-args = ["$left", "$right", "/leftreadonly", "/rightreadonly", "/expandall"]
edit-args = ["$left", "$right", "/leftreadonly", "/expandall"]
merge-args = ["$left", "$right", "$base", "$output", "/expandall", "/automerge", "/reviewconflicts"]
# merge-args = ["$left", "$right", "$base", "$output", "/expandall", "/automerge"]

[merge-tools.bc-3]
program = "bcomp"
edit-args = ["$left", "$right", "/expandall", "/mergeoutput=$right", "/leftreadonly", "/rightreadonly"]

[merge-tools.difft]
edit-args = ["$left", "$right", "--color", "always"]

[revsets]
log = 'slice'

[revset-aliases]
'default' = '@ | ancestors((immutable_heads() ~ no_log_heads()).., 2) | heads((immutable_heads() ~ no_log_heads()))'

'open()' = 'mine() ~ ::immutable_heads()'
'wip()' = 'description(glob:"wip:*") ~ ::immutable_heads()'
'merged()' = '(branches() & ..trunk()) ~ trunk()'
'mergedr()' = '(remote_branches() & ..trunk()) ~ trunk()'

'immutable_heads()' = 'trunk() | tags() | additional_immutable_heads()'
'additional_immutable_heads()' = 'none()'

# set this in a repo to hide their ancestors from the default log revset
'no_log_heads()' = 'none()'

# view a revision's ancestry back to where it diverged from trunk()
'stack' = 'stack(@)'
'stack(from)' = '(trunk()..from) | ancestors((trunk()..from), 2)'

# view a revision's ancestry back to where it diverged from trunk(), plus
# any revisions descended from it
'slice' = 'slice(@)'
'slice(from)' = '(trunk()..from):: | ancestors((trunk()..from)::, 2)'

'branches_in_stack()' = 'remote_branches() & slice()'

# anything that hasn't been pushed yet
'behind' = 'remote_branches().. | ancestors(remote_branches().., 2)'

'hanging' = "branches() | remote_branches() | tags()"
floating = "all() ~ ::branches()"

# @ is annoying to type in PowerShell
HEAD = "@"
at = "@"
wc = "@"

[aliases]
logr = ["log", "--reversed"]
logc = ["log", "--reversed", "-T", "builtin_log_comfortable"]

# viewing history
open = ["logr", "-r", "open()"]
hanging = ["logr", "-r", "ancestors(hanging.., 2)"]

dt = ["diff", "--tool", "bc"]
difftool = ["diff", "--tool", "bc"]

diffbranch = ["diff", "--from", "trunk()"]

# navigating
n = ["next", "--edit"]
p = ["prev", "--edit"]

# bring a branch up to date with trunk()
# works with `jj sync` or with `-b REV`
sync = ["rebase", "--skip-empty", "-d", "trunk()"]

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'
